version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo INSTALL source NPM dependencies...
      - npm install
  pre_build:
    commands:
      - echo PRE_BUILD tasks...
  build:
    commands:
      - echo BUILD started on `date`
      - echo BUILD Zipping deployment package...
      - zip -r -q ../lambda-autentication.zip .
    post_build:
      commands:
      - echo POST_BUILD Updating lambda Function...
      - aws lambda update-function-code --function-name lambda-autentication --zip-file fileb://lambda-autentication.zip
      - echo BUILD completed on `date`  
artifacts:
  type: zip
  files:
    - package.json
    - package-lock.json
    - "build/**/*"
    - .ebextensions/**/*