version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing phases INSTALL source NPM dependencies...
      - npm install
  pre_build:
    commands:
      - echo Installing phases PRE_BUILD source NPM dependencies...
  build:
    commands:
      - echo Build started on `date`
      - echo "Zipping deployment package..."
      - zip -r ../lambda-autentication.zip .
    post_build:
      commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name lambda-autentication --zip-file fileb://lambda-autentication.zip
      - echo Build completed on `date`  
artifacts:
  type: zip
  files:
    - package.json
    - package-lock.json
    - "build/**/*"
    - .ebextensions/**/*